### ISSUE TITLE
kitchen-ansible fails install due to docs on ruby2.6

### ISSUE THREAD

**Issue by b00ga** [neillturner/kitchen-ansible#303]
Gem install of kitchen-ansible w/ ruby 2.6 failed due to a doc build error. (CentOS7, ruby 2.6.2p47 built with ruby-build, kitchen-ansible 0.49.1).

```
Parsing documentation for kitchen-ansible-0.49.1
Before reporting this, could you check that the file you're documenting
has proper syntax:

  /usr/local/ruby/2.6.2/bin/ruby -c lib/kitchen/provisioner/ansible/os/alpine.rb

RDoc is not a full Ruby parser and will fail when fed invalid ruby programs.

The internal error was:

        (NoMethodError) undefined method `[]' for nil:NilClass

ERROR:  While executing gem ... (NoMethodError)
    undefined method `[]' for nil:NilClass
```

Worked around for now with `gem install --no-document kitchen-ansible`

**Comment by neillturner** [comment]
i will fix for ruby 2.6

**Comment by neillturner** [comment]
fixed in version 0.50.0

**Comment by gawbul** [comment]
Still having this issue with version 0.50.0:

```
$ gem install kitchen-ansible
Fetching kitchen-ansible-0.50.0.gem
Successfully installed kitchen-ansible-0.50.0
Parsing documentation for kitchen-ansible-0.50.0
Before reporting this, could you check that the file you're documenting
has proper syntax:

  /Users/stephenmoss/.rbenv/versions/2.6.3/bin/ruby -c lib/kitchen/provisioner/ansible/os/alpine.rb

RDoc is not a full Ruby parser and will fail when fed invalid ruby programs.

The internal error was:

	(NoMethodError) undefined method `[]' for nil:NilClass

ERROR:  While executing gem ... (NoMethodError)
    undefined method `[]' for nil:NilClass
```

Running with ruby 2.6.3:

```
$ ruby -v
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
```

**Comment by rtphokie** [comment]
I'm still having the problem with version 0.50.1

```
$ gem install kitchen-ansible
Successfully installed kitchen-ansible-0.50.1
Parsing documentation for kitchen-ansible-0.50.1
Before reporting this, could you check that the file you're documenting
has proper syntax:

  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -c lib/kitchen/provisioner/ansible/os/alpine.rb

RDoc is not a full Ruby parser and will fail when fed invalid ruby programs.

The internal error was:

	(NoMethodError) undefined method `[]' for nil:NilClass

ERROR:  While executing gem ... (NoMethodError)
```

running with ruby 2.5.3

```
% ruby -v
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
```

**Comment by petracvv** [comment]
This looks like a problem with how rdoc is parsing that file. I updated to the latest rdoc gem with `gem update rdoc` and the problem went away so whatever parsing error was there is now fixed.

**Comment by getjack** [comment]
I can confirm that for Ruby 2.6.5 the `gem update rdoc` will fix the issue
